#!/bin/python
import subprocess

command = subprocess.run(['acpi', '--everything'], capture_output=True)
output = command.stdout.decode('utf8').splitlines()

battery_capacities = [
        int(bc.split()[4])
        for bc 
        in output 
        if ('Battery' in bc) and ('capacity' in bc)
]

battery_charging_percentage = [
        int(bcp.split(',')[1][:-1].strip())
        for bcp 
        in output 
        if ('Battery' in bcp) and 
           (('Unknown' in bcp) or ('Discharging') in bcp) and
           ('%' in bcp)
]

res = 0
for bc, bcp in zip(battery_capacities, battery_charging_percentage):
    res += bcp * (bc / sum(battery_capacities))


print("{}%".format(int(res)))
